version: '3.8'

services:
  # MongoDB database
  db:
    image: mongo:6
    ports:
      - '27017:27017'  # Expose port 27017 for MongoDB
    environment:
      MONGO_PASSWORD: Shanks0004000  # Persistent storage for MongoDB data



  # Next.js application
  web:
    build:
      context: .
    image: nextjs-dev
    ports:
      - '3000:3000'  # Expose port 3000 for the Next.js app
    depends_on:
      - db
    environment:
      DATABASE_URL: mongodb+srv://sharibkhan939:Shanks0004000@cluster0.hwf1a.mongodb.net/thread?retryWrites=true&w=majority&appName=Cluster0
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src 
          ignore:
            - node_modules/  
        - action: rebuild
          path: package.json

